# THINGS

ALG: 'her'

# EXPERIMENT PARAMS
NUM_SEEDS: 1
SEED: 1

# logggin
MAX_EPISODE_LOG_LEN: 40


# RUN PARAMS
TOTAL_TIMESTEPS: 100_000_000
NUM_ENVS: 32
EVAL_STEPS: 100
EVAL_EPISODES: 100
LEARNER_LOG_PERIOD: 500
LEARNER_EXTRA_LOG_PERIOD: 5_000
EVAL_LOG_PERIOD: 25
EVAL_LOG_PERIOD_ACTOR: 0
GRADIENT_LOG_PERIOD: 0

# NEURAL NET PARAMS
EMBED_HIDDEN_DIM: 64
NUM_MLP_LAYERS: 0
NUM_EMBED_LAYERS: 0
MLP_HIDDEN_DIM: 256
AGENT_RNN_DIM: 256
ACTIVATION: 'leaky_relu'
NUM_Q_LAYERS: 2
Q_HIDDEN_DIM: 512
AUX_COEFF: 1e-5

# ALGO PARAMS
BUFFER_SIZE: 50_000
TOTAL_BATCH_SIZE: 1280
BUFFER_BATCH_SIZE: 32
SAMPLE_LENGTH: null
LEARNING_STARTS: 10_000
TRAINING_INTERVAL: 5
STEP_COST: 0

# HER PARAMS
HER_COEFF: 1.0
ALL_GOALS_COEFF: 1.0 # new parameter introduced for large mazes
ALL_GOALS_LAMBDA: 0.3
GOAL_BETA: 10.
NUM_HER_GOALS: 1
POSITION_GOALS: FALSE
TERMINATE_ON_REWARD: FALSE
SARSA_TD: FALSE
CQL_ALPHA: 0.0
CQL_TEMP: 1.0

FIXED_EPSILON: 2 # range of epsilons
EPSILON_START: 1.0
EPSILON_FINISH: 0.1
EPSILON_ANNEAL_TIME: null
MAX_GRAD_NORM: 80
TARGET_UPDATE_INTERVAL: 1_000
LR: 0.0001
LR_LINEAR_DECAY: FALSE
EPS_ADAM: 0.00001

GAMMA: 0.99
